# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip_json_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('ip', models.CharField(max_length=50)),
                ('downtime', models.CharField(max_length=50)),
                ('ip_json', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='json_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('ip_info', models.CharField(max_length=254)),
                ('downtime', models.CharField(max_length=50)),
                ('json', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=254)),
                ('url', models.CharField(max_length=254)),
                ('key', models.CharField(max_length=254)),
            ],
        ),
    ]
